### ISSUE TITLE
my handle bars is not displaying the table after debugging I get to know that my handlebar is working fine till ui, but not displaying the table on browser

### ISSUE THREAD

**Issue by isharma-sharma** [ga-wdi-boston/capstone-project#743] opened 2017-07-19 01:44 UTC
my html 
``````
  <div id="request-table" class="table-responsive request-table">
          <table class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>name</th>
                <th>Contactno</th>
                <th>Address:</th>
                <th>MESSAGE:</th>
              </tr>
            </thead>
            <tbody id="requestadd" class="request-row">

            </tbody>
          </table>
        </div>
````````
handlebar file  for request
``````
{{#each requests as |request|}}
<tr data-id="{{request.id}}">
<td data-id="{{recipe.id}}"><button id="deleteRequest{{request.id}}" class="btn btn-default deleteRequest">Delete</button></td>
<td class="rname" name="[request][name]"><{{request.name}}</td>
<td class="rcontact" name="[request][telephone]"><{{request.telephone}}</td>
<td class="raddresss" name="[request][addresss]"><{{request.addresss}}</td>
<td class="rmessage" name="[request][message]"><{{request.message}}</td>
</tr>
{{/each}}
```````
event .js
```````
const onGetAllRequest = function (event) {
  event.preventDefault()
  // const data = getFormFields(event.target)
  api.getAllRequest()
    .then(ui.getAllRequestSuccess)
    .catch(ui.getAllRequestFailure)
}
`````````
api.js
````````
const getAllRequest = function () {
  return $.ajax({
    url: config.apiOrigin + '/requests',
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + store.userToken
    }
  })
}
```````
ui file
```````
const getAllRequestSuccess = (data) => {
  console.log(data)
  debugger
  $('.request-table').empty()
  const showrequestHtml = showRequestTemplate({ requests: data.requests })
  console.log(showrequestHtml)
  $('#requestadd').html(showrequestHtml)
  $('#request-table').show()
}
````````

**Comment by isharma-sharma** [comment] 2017-07-19 01:45
my console response
```````

<tr data-id="1">
<td data-id=""><button id="deleteRequest1" class="btn btn-default deleteRequest">Delete</button></td>
<td class="rname" name="[request][name]"><pooja</td>
<td class="rcontact" name="[request][telephone]"><12345</td>
<td class="raddresss" name="[request][addresss]"><</td>
<td class="rmessage" name="[request][message]"><</td>
</tr>
<tr data-id="2">
<td data-id=""><button id="deleteRequest2" class="btn btn-default deleteRequest">Delete</button></td>
<td class="rname" name="[request][name]"><pooja</td>
<td class="rcontact" name="[request][telephone]"><12345</td>
<td class="raddresss" name="[request][addresss]"><</td>
<td class="rmessage" name="[request][message]"><</td>
</tr>
<tr data-id="3">
<td data-id=""><button id="deleteRequest3" class="btn btn-default deleteRequest">Delete</button></td>
<td class="rname" name="[request][name]"><o</td>
<td class="rcontact" name="[request][telephone]"><1</td>
<td class="raddresss" name="[request][addresss]"><</td>
<td class="rmessage" name="[request][message]"><w</td>
</tr>

**Comment by benjimelito** [comment] 2017-07-19 13:41
One thing I'm noticing is that you're using `.html` rather than using `.append` when you are attempting to add the html. Also, I probably wouldn't give your request-table div an `id` AND a `class` of  `request-table`.

**Comment by benjimelito** [comment] 2017-07-19 13:43
It looks like the html is being returned correctly, as you've identified I believe the issue is simply appending it to the DOM. One more thing: Do you need to be clearing and showing your request-table div every time that function runs?

**Comment by isharma-sharma** [comment] 2017-07-19 13:44
i was facing the same problem so when i did html it resolved the thing, i tried . with .append also i was getting the same response  on console nothing on browser

**Comment by isharma-sharma** [comment] 2017-07-19 13:45
const getAllRequestSuccess = (data) => {
  console.log(data)
  debugger
  $('.request-table').empty()
  const showrequestHtml = showRequestTemplate({ requests: data.requests })
  console.log(showrequestHtml)
  $('#requestadd').append(showrequestHtml)
  $('#request-table').show()
}

**Comment by benjimelito** [comment] 2017-07-19 13:56
If you remove the `$('.request-table').empty()` and `$('#request-table').show()` statements, does this change anything?

**Comment by isharma-sharma** [comment] 2017-07-19 14:08
this thing worked but the delete  button is  not removing the request at that time it is deleted u can see that thing after sign-in again

**Comment by benjimelito** [comment] 2017-07-19 14:22
So this is sort of sounding like a separate issue, but are you attaching a click handler to the delete button in `events.js` ? Look at line 20 here: https://git.generalassemb.ly/ga-wdi-boston/handlebars/blob/master/assets/scripts/books/events.js

**Comment by isharma-sharma** [comment] 2017-07-19 14:31
my event.js
``````
const onDeleteRequest = function (event) {
  event.preventDefault()
  console.log(event)
  const id = $(event.target).parent().parent().attr('data-id')
  console.log('this is what we need')
  console.log(id)
  api.deleteRequest(id)
   .then(ui.DeleteRequestSuccess)
   .catch(ui.DeleteRequestFailure)
}
here i ma invoking it
`````
$('body').on('click', '.deleteRequest', onDeleteRequest)
`````
api.js
`````
const deleteRequest = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/requests/' + data,
    method: 'DELETE',
    headers: {
      Authorization: 'Token token=' + store.userToken
    }
  })
  .then((response) => {
    $("td[data-id='" + data + "']").remove()
  })
}

**Comment by benjimelito** [comment] 2017-07-19 14:38
I think this is a separate issue at this point, would you mind closing this one and opening another?

**Closed as completed** 2017-07-19 14:41 UTC
